//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPT.Test.JECP.BackEnd.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionesEstudiantes
    {
        public int Id { get; set; }
        public int IdEstudiante { get; set; }
        public int IdAsignacion { get; set; }
    
        public virtual Asignaciones Asignaciones { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
