USE [master]
GO

/****** Object:  Database [Escuela]    Script Date: 02/22/2021 19:43:22 ******/
--ESTOS DATOS HAY QUE CAMBIAR LOS DEL DIRECTORIO PROGRAM FILES U OMITIRLOS
--ABAJO ESTAN LOS SCRIPTS DE CREACION DE TABLAS
CREATE DATABASE [Escuela] ON  PRIMARY 
( NAME = N'Escuela', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER2008\MSSQL\DATA\Escuela.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Escuela_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER2008\MSSQL\DATA\Escuela_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Escuela] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Escuela].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Escuela] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Escuela] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Escuela] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Escuela] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Escuela] SET ARITHABORT OFF 
GO

ALTER DATABASE [Escuela] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Escuela] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Escuela] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Escuela] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Escuela] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Escuela] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Escuela] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Escuela] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Escuela] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Escuela] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Escuela] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Escuela] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Escuela] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Escuela] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Escuela] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Escuela] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Escuela] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Escuela] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Escuela] SET  READ_WRITE 
GO

ALTER DATABASE [Escuela] SET RECOVERY FULL 
GO

ALTER DATABASE [Escuela] SET  MULTI_USER 
GO

ALTER DATABASE [Escuela] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Escuela] SET DB_CHAINING OFF 
GO

CREATE TABLE [dbo].[Estudiantes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](60) NOT NULL,
	[FechaNacimiento] [datetime] NOT NULL,
 CONSTRAINT [PK_Estudiantes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Asignaciones](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](60) NOT NULL,
 CONSTRAINT [PK_Asignaciones] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[AsignacionesEstudiantes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdEstudiante] [int] NOT NULL,
	[IdAsignacion] [int] NOT NULL,
 CONSTRAINT [PK_AsignacionesEstudiantes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AsignacionesEstudiantes]  WITH CHECK ADD  CONSTRAINT [FK_AsignacionesEstudiantes_Asignaciones] FOREIGN KEY([IdAsignacion])
REFERENCES [dbo].[Asignaciones] ([Id])
GO

ALTER TABLE [dbo].[AsignacionesEstudiantes] CHECK CONSTRAINT [FK_AsignacionesEstudiantes_Asignaciones]
GO

ALTER TABLE [dbo].[AsignacionesEstudiantes]  WITH CHECK ADD  CONSTRAINT [FK_AsignacionesEstudiantes_Estudiantes] FOREIGN KEY([IdEstudiante])
REFERENCES [dbo].[Estudiantes] ([Id])
GO

ALTER TABLE [dbo].[AsignacionesEstudiantes] CHECK CONSTRAINT [FK_AsignacionesEstudiantes_Estudiantes]
GO



